### ISSUE TITLE
add head, tail, slice functions to pycylon table (may be to cylon table as well)

### ISSUE THREAD

**Issue by nirandaperera** [cylondata/cylon#317]
Todo:

- [x] head (#592)
- [x] slice (#592)
- [x] tail (#592)
- [x] add cython bindings  (#619)
- [x] Update ` __getitem__` method in `pycylon.DataFrame`. For distributed head/ tail/ slice, pass an additional `CylonEnv` object to `__getitem__` method (#619)
```python
df = ....
df[5:100] # local slice 
df[:5] # local head 
df[:-5] # local tail 

df[5:100, env] # distributed slice
df[:5, env] # distributed head 
df[:-5, env] # distributed tail 
```

- [x] add python test (#619)

Reference - Design doc 
https://docs.google.com/document/d/1wQ3rVj5OBLXju5hf6FWlwyDGc65ync_LZVQ_QzsHX-c/edit

Reference GPU impl #512

**Comment by nirandaperera** [comment]
@arupcsedu Can you also add the cython/ python bindings for this? Sorry I forgot to add that requirement to this issue previously.

**Comment by arupcsedu** [comment]
Sure. Let me check the requirements and get back to you.
